### ISSUE TITLE
invalid_grant

### ISSUE THREAD

**Issue by rippo** [XeroAPI/Xero-Postman-Tutorial-PKCE-Edition#2]
Hi I am trying this out and all I ever get back from step 7 is:-
```
{
    "error": "invalid_grant"
}
``` 

Am I doing something wrong?

![2020-06-12_15-34-07](https://user-images.githubusercontent.com/772549/84514669-4dacec80-acc3-11ea-8a39-bf7604e5d5fd.png)

**Comment by rippo** [comment]
Hi I have solved it, can you update your documentation to make this a little clearer.

e.g.
My string:  `hello-brown-cat-red-mat-brown-bear-red-fox-green-ball`
Code generated: `pO7sgLQByB-F6OEFKtSqwc-wS6p4oQ4OLlqPAgJp1VA`

In the Get Authorisation the code_verifier is what was created using the online tool 
https://tonyxu-io.github.io/pkce-generator/ e.g.
`pO7sgLQByB-F6OEFKtSqwc-wS6p4oQ4OLlqPAgJp1VA`

In the connect part, step 7, the code is the raw string you created
`hello-brown-cat-red-mat-brown-bear-red-fox-green-ball`

I was using the generated code both times! Also the docs on XERO doesn't make this clear.
https://developer.xero.com/documentation/oauth2/pkce-flow 

Thanks, this can be closed

(these codes where changed for security purposes!)

**Comment by MattR-Api** [comment]
Hi @rippo Thanks for the suggestion. We'll be sure to clarify that.
